## Case 7 - filtro e média em DataFrame

Você recebeu uma tabela com vendas de uma loja:

- produto: Notebook, Mouse, Teclado, Monitor  
- vendas: 12, 50, 30, 20  

Crie um código com pandas que:

- crie um DataFrame com essas informações  

- mostre apenas os produtos com vendas maiores que 20  

- mostre a média da coluna vendas  |

In [2]:
# Importando o pandas e criando um data frame
import pandas as pd

venda = pd.DataFrame({
    'produto': ["Notebook", "Mouse", "Teclado", "Monitor"],
    'vendas': [12, 50, 30, 20] 
})

venda

    produto  vendas
0  Notebook      12
1     Mouse      50
2   Teclado      30
3   Monitor      20

In [ ]:
# Filtrando os produtos com mais de 20 vendas
venda[venda['vendas'] > 20]

   produto  vendas
1    Mouse      50
2  Teclado      30

In [ ]:
# Somando a média da coluna vendas 
venda['vendas'].mean()

28.0