## Case 8 - criação de coluna calculada (faturamento)

Você recebeu dados de faturamento de uma loja:

- produto: Notebook, Mouse, Teclado, Monitor  
- preco: 3500, 80, 150, 900  
- quantidade_vendida: 3, 10, 5, 2  

Crie um código com pandas que:

- crie um DataFrame com esses dados  

- crie uma nova coluna chamada faturamento  
  - usando: preco * quantidade_vendida  

- mostre o DataFrame final

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

venda = pd.DataFrame({
    'produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor'],
    'preco': [3500, 80, 150, 900],
    'quantidade_vendida': [3, 10, 5, 2]
})

venda

    produto  preco  quantidade_vendida
0  Notebook   3500                   3
1     Mouse     80                  10
2   Teclado    150                   5
3   Monitor    900                   2

In [ ]:
# Criando uma nova coluna Faturamento apartir de outras colunas
venda['faturamento'] = venda['preco'] * venda['quantidade_vendida']

venda

    produto  preco  quantidade_vendida  faturamento
0  Notebook   3500                   3        10500
1     Mouse     80                  10          800
2   Teclado    150                   5          750
3   Monitor    900                   2         1800