## Case 47 — somar valor dos pedidos por cliente após o merge

Use as mesmas tabelas do exercício anterior e faça um código que:

- crie os dois DataFrames  
- faça o outer merge  
- mostre, para cada id_cliente:  
  - a quantidade de pedidos válidos  
  - a soma dos valores dos pedidos  
- use groupby(...).agg(...) com nomes personalizados

In [1]:
# Importando o pandas e criando um DataFrame
import pandas as pd

tb_1 = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4 ],
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela']
})

tb_2 = pd.DataFrame({
    'id_cliente': [1, 2, 2, 4, 5 ],
    'valor_pedido': [120, 250, 180, 300, 500]
})

df_junta = pd.merge(tb_1, tb_2, on='id_cliente', how='outer')

df_junta

   id_cliente     nome  valor_pedido
0           1      Ana         120.0
1           2    Bruno         250.0
2           2    Bruno         180.0
3           3   Carlos           NaN
4           4  Daniela         300.0
5           5      NaN         500.0

In [3]:
df_junta.groupby('id_cliente').agg(
    pedido_validos = ('valor_pedido', 'count'),
    total_valor_pedido = ('valor_pedido', 'sum')
    
).reset_index()

   id_cliente  pedido_validos  total_valor_pedido
0           1               1               120.0
1           2               2               430.0
2           3               0                 0.0
3           4               1               300.0
4           5               1               500.0