## Case 49 — ordenar o resumo

Use as mesmas tabelas e faça um código que:

- faça o outer merge  
- monte o resumo por cliente com:  
  - id_cliente  
  - nome  
  - qtd_pedidos_validos  
  - soma_valor_pedido  
- ordene o resultado pela soma_valor_pedido, do maior para o menor

In [1]:
# Importando o pandas e criando um DataFrame
import pandas as pd

tb_1 = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4 ],
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela']
})

tb_2 = pd.DataFrame({
    'id_cliente': [1, 2, 2, 4, 5 ],
    'valor_pedido': [120, 250, 180, 300, 500]
})

df_junta = pd.merge(tb_1, tb_2, on='id_cliente', how='outer')

df_junta

   id_cliente     nome  valor_pedido
0           1      Ana         120.0
1           2    Bruno         250.0
2           2    Bruno         180.0
3           3   Carlos           NaN
4           4  Daniela         300.0
5           5      NaN         500.0

In [ ]:
# Substitunindo valores null para aparecer no groupby. por padrão ele ignora e não mostra
df_junta['nome'] = df_junta['nome'].fillna('Desconhecido')

# agora criando o groupby para mostra id_cliente e o nomes agrupados pelas funcoes
# Depois renomeia as colunas para ficar mais apresentado
df_junta.groupby(['id_cliente', 'nome']).agg(
    qtd_pedidos_validos = ('valor_pedido', 'count'),
    soma_valor_pedido = ('valor_pedido', 'sum')

# Depois organizando do maior para o menor valor de soma_pedido_valido
).reset_index().sort_values(by='soma_valor_pedido', ascending=False)

   id_cliente          nome  qtd_pedidos_validos  soma_valor_pedido
4           5  Desconhecido                    1              500.0
1           2         Bruno                    2              430.0
3           4       Daniela                    1              300.0
0           1           Ana                    1              120.0
2           3        Carlos                    0                0.0