## Case 29 - uso de loc e iloc

Use estes dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, SP, RJ, SP  
- valor_pedido: 120, 250, 80, 300, 150  

Faça um código com pandas que:

- crie o DataFrame  
- usando iloc, mostre:  
  - a primeira linha  
- usando loc, mostre:  
  - apenas as linhas onde cidade == 'SP'  
- usando loc, mostre apenas as colunas:  
  - cliente  
  - valor_pedido  
- usando loc, mostre apenas os clientes de SP com suas colunas cliente e valor_pedido

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', 'SP', 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, 300, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP           120
1    Bruno     RJ           250
2   Carlos     SP            80
3  Daniela     RJ           300
4      Eva     SP           150

In [ ]:
# Seleciona a primeira linha do DataFrame pela posição numérica usando iloc.
clientes.iloc[0]

cliente         Ana
cidade           SP
valor_pedido    120
Name: 0, dtype: object

In [ ]:
# Seleciona todas as linhas, mas mostra apenas as colunas 'cliente' e 'valor_pedido'.
clientes.loc[:, ['cliente', 'valor_pedido']]

   cliente  valor_pedido
0      Ana           120
1    Bruno           250
2   Carlos            80
3  Daniela           300
4      Eva           150

In [ ]:
# Filtra e mostra apenas as linhas em que a cidade é SP.
clientes.loc[clientes['cidade'] == 'SP']

  cliente  valor_pedido
0     Ana           120
2  Carlos            80
4     Eva           150