## Case 30 - atualização de valores com loc

Use os mesmos dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, SP, RJ, SP  
- valor_pedido: 120, 250, 80, 300, 150  

Faça um código com pandas que:

- crie o DataFrame  
- usando loc, crie uma coluna chamada status  
- coloque "Normal" para todos os clientes  
- depois, usando loc, altere o status para "VIP" apenas para clientes com valor_pedido >= 200  
- mostre o DataFrame final

In [1]:
# Importando o pandas e criando um data frame
import pandas as pd

clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', 'SP', 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, 300, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP           120
1    Bruno     RJ           250
2   Carlos     SP            80
3  Daniela     RJ           300
4      Eva     SP           150

In [ ]:
# Cria a coluna 'status' e preenche todas as linhas com o valor 'Normal'
clientes.loc[:, 'status'] = 'Normal'

# Atualiza a coluna 'status' para 'VIP' apenas nos clientes com valor_pedido maior ou igual a 200.
clientes.loc[clientes['valor_pedido'] >= 200, 'status'] = 'VIP'

clientes

   cliente cidade  valor_pedido  status
0      Ana     SP           120  Normal
1    Bruno     RJ           250     VIP
2   Carlos     SP            80  Normal
3  Daniela     RJ           300     VIP
4      Eva     SP           150  Normal