## Case 31 - atualização de múltiplas colunas com loc

Use os mesmos dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, SP, RJ, SP  
- valor_pedido: 120, 250, 80, 300, 150  

Faça um código com pandas que:

- crie o DataFrame  
- crie uma coluna status com "Normal" para todos  
- crie uma coluna desconto com 0 para todos  
- usando loc, altere para os clientes com valor_pedido >= 200:  
  - status = "VIP"  
  - desconto = 10  
- mostre o DataFrame final

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', 'SP', 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, 300, 150,]
})

# Cria as colunas 'status' e 'desconto' com valores padrão para todos os clientes.
clientes['status'] = 'Normal'
clientes['desconto'] = 0

clientes

   cliente cidade  valor_pedido  status  desconto
0      Ana     SP           120  Normal         0
1    Bruno     RJ           250  Normal         0
2   Carlos     SP            80  Normal         0
3  Daniela     RJ           300  Normal         0
4      Eva     SP           150  Normal         0

In [ ]:
# Atualiza ao mesmo tempo as colunas 'status' e 'desconto' para os clientes
# com valor_pedido maior ou igual a 200.
clientes.loc[clientes['valor_pedido'] >= 200, ['status', 'desconto']] = ['VIP', 10] 

clientes

   cliente cidade  valor_pedido  status  desconto
0      Ana     SP           120  Normal         0
1    Bruno     RJ           250     VIP        10
2   Carlos     SP            80  Normal         0
3  Daniela     RJ           300     VIP        10
4      Eva     SP           150  Normal         0