## Case 33 - atualização com múltiplas condições

Use os mesmos dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, SP, RJ, SP  
- valor_pedido: 120, 250, 80, 300, 150  

Faça um código com pandas que:

- crie o DataFrame  
- crie uma coluna prioridade com "Normal" para todos  
- usando loc, altere prioridade para "Alta" apenas para clientes que:  
  - sejam da cidade RJ  
  - e tenham valor_pedido >= 250  
- mostre o DataFrame final

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', 'SP', 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, 300, 150,]
})

# Cria a coluna 'prioridade' com o valor padrão 'Normal' para todos os clientes.
clientes['prioridade'] = 'Normal'

clientes

   cliente cidade  valor_pedido prioridade
0      Ana     SP           120     Normal
1    Bruno     RJ           250     Normal
2   Carlos     SP            80     Normal
3  Daniela     RJ           300     Normal
4      Eva     SP           150     Normal

In [ ]:
# Atualiza a coluna 'prioridade' para 'Alta' apenas nos clientes da cidade RJ
# que também tenham valor_pedido maior ou igual a 250.
clientes.loc[(clientes['cidade'] == 'RJ') & (clientes['valor_pedido'] >= 250), 'prioridade'] = 'Alta'

clientes

   cliente cidade  valor_pedido prioridade
0      Ana     SP           120     Normal
1    Bruno     RJ           250       Alta
2   Carlos     SP            80     Normal
3  Daniela     RJ           300       Alta
4      Eva     SP           150     Normal