## Case 33 - filtro com loc usando ou

Use os mesmos dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, SP, RJ, SP  
- valor_pedido: 120, 250, 80, 300, 150  

Faça um código com pandas que:

- crie o DataFrame  
- crie uma coluna grupo com "Comum" para todos  
- usando loc, altere grupo para "Especial" para clientes que:  
  - estejam em RJ  
  - ou tenham valor_pedido < 100  
- mostre o DataFrame final

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', 'SP', 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, 300, 150,]
})

# Cria a coluna 'grupo' com o valor padrão 'Comum' para todos os clientes.
clientes['grupo'] = 'comum'

clientes

   cliente cidade  valor_pedido  grupo
0      Ana     SP           120  comum
1    Bruno     RJ           250  comum
2   Carlos     SP            80  comum
3  Daniela     RJ           300  comum
4      Eva     SP           150  comum

In [ ]:
# Atualiza a coluna 'grupo' para 'Especial' nos clientes que estejam em RJ
# ou tenham valor_pedido menor que 100.
clientes.loc[(clientes['cidade'] == 'RJ') | (clientes['valor_pedido'] < 100), 'grupo'] = 'Especial'

clientes

   cliente cidade  valor_pedido     grupo
0      Ana     SP           120     comum
1    Bruno     RJ           250  Especial
2   Carlos     SP            80  Especial
3  Daniela     RJ           300  Especial
4      Eva     SP           150     comum