## Case 19 - faturamento, categorização e ordenação

Uma loja quer analisar melhor seus produtos.

Você recebeu os dados:

- produto: Notebook, Mouse, Teclado, Monitor, Webcam  
- preco: 3500, 80, 150, 900, 250  
- quantidade_vendida: 3, 10, 5, 2, 8  

Faça um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada faturamento  
  - usando preco * quantidade_vendida  

- crie uma coluna chamada categoria  
  - "Alta" para faturamento maior ou igual a 1000  
  - "Baixa" para faturamento menor que 1000  

- mostre apenas os produtos com categoria Alta  

- mostre esses produtos ordenados do maior faturamento para o menor

In [2]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

produtos = pd.DataFrame({
    'produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Webcam'],
    'preco': [3500, 80, 150, 900, 250],
    'quantidade_vendida': [3, 10, 5, 2, 8]
})

produtos

    produto  preco  quantidade_vendida
0  Notebook   3500                   3
1     Mouse     80                  10
2   Teclado    150                   5
3   Monitor    900                   2
4    Webcam    250                   8

In [ ]:
# Calcula o faturamento de cada produto multiplicando o preço pela quantidade vendida.
# Depois classifica os produtos em categoria Alta ou Baixa com base no faturamento.
# Por fim, filtra apenas os produtos da categoria Alta do maior para o menor.

produtos['faturamento'] = produtos['preco'] * produtos['quantidade_vendida']
produtos['categoria'] = np.where(produtos['faturamento'] >= 1000, 'Alta', 'Baixa')

produtos[produtos['categoria'] == 'Alta'].sort_values(by='faturamento', ascending=False)

    produto  preco  quantidade_vendida  faturamento categoria
0  Notebook   3500                   3        10500      Alta
4    Webcam    250                   8         2000      Alta
3   Monitor    900                   2         1800      Alta