## Case 20 - ticket médio e classificação de clientes

Uma empresa quer descobrir quais clientes são mais valiosos.

Você recebeu os dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva, Felipe  
- valor_pedido: 120, 250, 80, 300, 150, 500  
- quantidade_itens: 2, 5, 1, 6, 3, 8  

Faça um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada ticket_medio_item  
  - usando: valor_pedido / quantidade_itens  

- crie uma coluna chamada perfil  
  - "Premium" para pedidos com valor_pedido >= 250 e quantidade_itens >= 5  
  - "Padrão" para os demais  

- mostre apenas os clientes com perfil Premium  

- ordene esse resultado do maior valor_pedido para o menor

In [ ]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva', 'Felipe'],
    'valor_pedido': [120, 250, 80, 300, 150, 500],
    'quantidade_itens': [2, 5, 1, 6, 3, 8]
})

clientes

   cliente  valor_pedido  quantidade_itens
0      Ana           120                 2
1    Bruno           250                 5
2   Carlos            80                 1
3  Daniela           300                 6
4      Eva           150                 3
5   Felipe           500                 8

In [ ]:
# Calcula o ticket médio por item dividindo o valor do pedido pela quantidade de itens.
clientes['ticket_medio_item'] = clientes['valor_pedido'] / clientes['quantidade_itens']

# Classifica o cliente como Premium quando o valor do pedido é pelo menos 250
# e a quantidade de itens é pelo menos 5; caso contrário, recebe o perfil Padrão.
clientes['perfil'] = np.where((clientes['valor_pedido'] >= 250) & (clientes['quantidade_itens'] >= 5), 'Premium', 'Padrão')

# Filtra apenas os clientes Premium e ordena do maior valor de pedido para o menor.
clientes[clientes['perfil'] == 'Premium'].sort_values(by='valor_pedido', ascending=False)

   cliente  valor_pedido  quantidade_itens  ticket_medio_item   perfil
5   Felipe           500                 8               62.5  Premium
3  Daniela           300                 6               50.0  Premium
1    Bruno           250                 5               50.0  Premium