## Case 22 - groupby, filtro e ordenação

Você recebeu os dados:

- **cliente:** Ana, Bruno, Carlos, Daniela, Eva, Felipe  
- **cidade:** SP, RJ, SP, RJ, SP, RJ  
- **valor_pedido:** 120, 250, 80, 300, 150, 500  

Faça um código com pandas + NumPy que:

- crie um DataFrame  
- crie uma coluna chamada **categoria**  
  - "Alto" para valor_pedido >= 200  
  - "Baixo" para os demais  
- mostre a média de valor_pedido por cidade  
- mostre apenas os clientes com categoria "Alto"  
- ordene esses clientes do maior valor_pedido para o menor

In [ ]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva', 'Felipe'],
    'cidade': ['SP', 'RJ', 'SP', 'RJ', 'SP', 'RJ'],
    'valor_pedido': [120, 250, 80, 300, 150, 500 ]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP           120
1    Bruno     RJ           250
2   Carlos     SP            80
3  Daniela     RJ           300
4      Eva     SP           150
5   Felipe     RJ           500

In [ ]:
# Cria a coluna 'categoria', classificando os pedidos em Alto ou Baixo conforme o valor do pedido.
clientes['categoria'] = np.where(clientes['valor_pedido'] >= 200, 'Alto', 'Baixo')

# Filtra apenas os clientes com categoria Alto e ordena do maior valor de pedido para o menor.
clientes[clientes['categoria'] == 'Alto'].sort_values(by='valor_pedido', ascending=False)

   cliente cidade  valor_pedido categoria
5   Felipe     RJ           500      Alto
3  Daniela     RJ           300      Alto
1    Bruno     RJ           250      Alto

In [ ]:
# Agrupa os dados por cidade e calcula a média do valor dos pedidos em cada uma.
clientes.groupby('cidade')['valor_pedido'].mean()

cidade
RJ    350.000000
SP    116.666667
Name: valor_pedido, dtype: float64