## Case 9 - filtro e criação de coluna condicional

Você recebeu o DataFrame abaixo sobre alunos:

- nome: Ana, Bruno, Carlos, Daniela  
- nota: 8.5, 6.0, 7.5, 9.0  

Crie um código com pandas que:

- crie esse DataFrame  

- mostre apenas os alunos com nota maior ou igual a 7  

- crie uma nova coluna chamada aprovado  
  - regra:  
    - True para nota maior ou igual a 7  
    - False para nota menor que 7  

- mostre o DataFrame final

In [12]:
# Importando o pandas e criando um data frame
import pandas as pd

notas = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela'],
    'nota': [8.5, 6.0, 7.5, 9.0]
})

notas

      nome  nota
0      Ana   8.5
1    Bruno   6.0
2   Carlos   7.5
3  Daniela   9.0

In [13]:
# Filtrando os alunos com notas maiores ou igual a 7
notas[notas['nota'] >= 7]

      nome  nota
0      Ana   8.5
2   Carlos   7.5
3  Daniela   9.0

In [16]:
# Criando uma nova coluna apenas com a mascara booleana
notas['aprovado'] = notas['nota'] >= 7 

notas

      nome  nota  aprovado
0      Ana   8.5      True
1    Bruno   6.0     False
2   Carlos   7.5      True
3  Daniela   9.0      True