## Case 10 - média e coluna condicional

Você recebeu dados de temperatura de uma semana:

- dia: Seg, Ter, Qua, Qui, Sex  
- temperatura: 30, 28, 31, 27, 29  

Crie um código com pandas que:

- crie um DataFrame com esses dados  

- mostre apenas os dias com temperatura maior que a média  

- mostre o valor da média da temperatura  

- crie uma nova coluna chamada acima_da_media  
  - com True para temperaturas maiores que a média  
  - e False para as demais

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

df_temp = pd.DataFrame({
    'dia': ['Seg', 'Ter', 'Qua', 'Qui', 'Sex'],
    'temperatura': [30, 28, 31, 27, 29]
})

df_temp

   dia  temperatura
0  Seg           30
1  Ter           28
2  Qua           31
3  Qui           27
4  Sex           29

In [ ]:
# Filtrando valores maiores que a média
df_temp[df_temp['temperatura'] > df_temp['temperatura'].mean()]

   dia  temperatura
0  Seg           30
2  Qua           31

In [ ]:
# mostrando a média 
df_temp['temperatura'].mean()

29.0

In [ ]:
# Criando uma nova coluna apenas com a mascara booleana
df_temp['acima_da_media'] = df_temp['temperatura'] > df_temp['temperatura'].mean()

df_temp

   dia  temperatura  acima_da_media
0  Seg           30            True
1  Ter           28           False
2  Qua           31            True
3  Qui           27           False
4  Sex           29           False