## Case 11 - cálculo de colunas e filtro

Você trabalha com dados de funcionários e recebeu esta tabela:

- nome: Ana, Bruno, Carlos, Daniela  
- salario: 2500, 1800, 3200, 2100  

Crie um código com pandas que:

- crie um DataFrame com esses dados  

- crie uma nova coluna chamada bonus  
  - regra: 10% do salário  

- crie uma nova coluna chamada salario_total  
  - regra: salario + bonus  

- mostre apenas os funcionários com salario_total maior que 2500

In [1]:
# Importando o pandas e criando um data frame
import pandas as pd

funcionario = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela'],
    'salario': [2500, 1800, 3200, 2100]
})

funcionario

      nome  salario
0      Ana     2500
1    Bruno     1800
2   Carlos     3200
3  Daniela     2100

In [3]:
# Criando as novas colunas bonus e salario_total
funcionario['bonus'] = funcionario['salario'] * 0.10
funcionario['salario_total'] = funcionario['salario'] + funcionario['bonus']

funcionario

      nome  salario  bonus  salario_total
0      Ana     2500  250.0         2750.0
1    Bruno     1800  180.0         1980.0
2   Carlos     3200  320.0         3520.0
3  Daniela     2100  210.0         2310.0

In [ ]:
# Filtrando apenas funcionários que recebam > 2500
funcionario[funcionario['salario_total'] > 2500]

     nome  salario  bonus  salario_total
0     Ana     2500  250.0         2750.0
2  Carlos     3200  320.0         3520.0