## Case 12 - coluna categórica e filtro

Uma escola quer classificar o desempenho dos alunos.

Você recebeu os dados:

- nome: Ana, Bruno, Carlos, Daniela, Eva  
- nota: 8.5, 6.0, 7.5, 9.0, 5.5  

Crie um código com pandas que:

- crie um DataFrame  

- crie uma coluna chamada situacao  
  - "Aprovado" para nota maior ou igual a 7  
  - "Reprovado" para nota menor que 7  

- mostre apenas os alunos reprovados

In [6]:
# Importando o pandas e criando um data frame
import pandas as pd
import numpy as np

notas = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'nota': [8.5, 6.0, 7.5, 9.0, 5.5]
})

notas

      nome  nota
0      Ana   8.5
1    Bruno   6.0
2   Carlos   7.5
3  Daniela   9.0
4      Eva   5.5

In [10]:
# Criando uma coluna com condição com np.where
notas['situacao'] = np.where(notas['nota'] >= 7, 'aprovado', 'reprovado')

notas

      nome  nota   situacao
0      Ana   8.5   aprovado
1    Bruno   6.0  reprovado
2   Carlos   7.5   aprovado
3  Daniela   9.0   aprovado
4      Eva   5.5  reprovado

In [11]:
# Criando um filtro onde mostre apenas os alunos reprovado
notas[notas['situacao'] == 'reprovado']

    nome  nota   situacao
1  Bruno   6.0  reprovado
4    Eva   5.5  reprovado