## Case 13 - categorização de preços com NumPy

Uma loja quer identificar produtos caros.

Você recebeu os dados:

- produto: Notebook, Mouse, Teclado, Monitor, Webcam  
- preco: 3500, 80, 150, 900, 250  

Crie um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada categoria_preco  
  - "Caro" para produtos com preço maior que 500  
  - "Barato" para os demais  

- mostre apenas os produtos classificados como Caro

In [ ]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

produtos = pd.DataFrame({
    'produtos': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Webcam'],
    'preco': [3500, 80, 150, 900, 250]
})

produtos

   produtos  preco
0  Notebook   3500
1     Mouse     80
2   Teclado    150
3   Monitor    900
4    Webcam    250

In [5]:
# Criando uma nova coluna usando o np.where como filtro e mostrando apenas produtos considerados caro
produtos['categoria_preco'] = np.where(produtos['preco'] > 500, 'caro', 'barato')
produtos[produtos['categoria_preco'] == 'caro']

   produtos  preco categoria_preco
0  Notebook   3500            caro
3   Monitor    900            caro