## Case 14 - meta de vendas com coluna categórica

Uma empresa quer analisar o desempenho de vendedores.

Você recebeu os dados:

- vendedor: Ana, Bruno, Carlos, Daniela, Eva  
- vendas: 120, 80, 150, 90, 110  

Crie um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada meta_batida  
  - "Sim" para vendedores com vendas maiores ou iguais a 100  
  - "Não" para os demais  

- mostre apenas os vendedores que bateram a meta

In [ ]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

vendedor = pd.DataFrame({
    'vendedor': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'vendas': [120, 80, 150, 90, 110]
})

vendedor

  vendedor  vendas
0      Ana     120
1    Bruno      80
2   Carlos     150
3  Daniela      90
4      Eva     110

In [ ]:
# Criando uma nova coluna usando o np.where como filtro e mostrando apenas os vendedores que bateram a meta
vendedor['meta_batida'] = np.where(vendedor['vendas'] >= 100, 'Sim', 'Não')
vendedor[vendedor['meta_batida'] == 'Sim']

  vendedor  vendas meta_batida
0      Ana     120         Sim
2   Carlos     150         Sim
4      Eva     110         Sim