## Case 15 - classificação em múltiplas faixas

Uma escola quer classificar os alunos em 3 faixas.

Dados:

- nome: Ana, Bruno, Carlos, Daniela, Eva  
- nota: 8.5, 6.0, 7.5, 9.0, 5.5  

Crie um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada faixa com esta regra:  
  - "Alta" para nota maior ou igual a 8  
  - "Média" para nota maior ou igual a 6 e menor que 8  
  - "Baixa" para nota menor que 6  

- mostre o DataFrame final

In [ ]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

notas = pd.DataFrame({
    'nome': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'nota': [8.5, 6.0, 7.5, 9.0, 5.5]
})

notas

      nome  nota
0      Ana   8.5
1    Bruno   6.0
2   Carlos   7.5
3  Daniela   9.0
4      Eva   5.5

In [ ]:
# 'condicao' reúne as regras booleanas para classificar as notas.
# 'valores' define o texto que será atribuído quando cada regra for satisfeita.
# np.select aplica as condições em ordem e cria a coluna 'faixa';
# caso nenhuma condição seja atendida, o valor padrão será 'Baixa'.

condicao = [
    notas['nota'] >= 8,
    notas['nota'] >= 6,
]

valores = ['Alta', 'Média']

notas['faixa'] = np.select(condicao, valores, default='Baixa') # defautl seria o padrao, então tudo que não mudar pelas condições sera baixa

notas

      nome  nota  faixa
0      Ana   8.5   Alta
1    Bruno   6.0  Média
2   Carlos   7.5  Média
3  Daniela   9.0   Alta
4      Eva   5.5  Baixa