## Case 16 - classificação de estoque

Uma loja quer classificar o estoque dos produtos.

Você recebeu os dados:

- produto: Notebook, Mouse, Teclado, Monitor, Webcam  
- estoque: 3, 15, 8, 2, 12  

Crie um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada nivel_estoque com esta regra:  
  - "Baixo" para estoque menor que 5  
  - "Médio" para estoque maior ou igual a 5 e menor que 10  
  - "Alto" para estoque maior ou igual a 10  

- mostre o DataFrame final

In [1]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

produtos = pd.DataFrame({
    'produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Webcam'],
    'estoque': [3, 15, 8, 2, 12]
})

produtos

    produto  estoque
0  Notebook        3
1     Mouse       15
2   Teclado        8
3   Monitor        2
4    Webcam       12

In [ ]:
# 'condicao' reúne as regras booleanas para classificar as notas.
# 'valores' define o texto que será atribuído quando cada regra for satisfeita.
# np.select aplica as condições em ordem e cria a coluna 'faixa';
filtro = [
    produtos['estoque'] < 5,
    (produtos['estoque'] >= 5) & (produtos['estoque'] < 10),
    produtos['estoque'] >= 10
]

valores = ['Baixo', 'Médio', 'Alto']

produtos['nivel_estoque'] = np.select(filtro, valores)

produtos

    produto  estoque nivel_estoque
0  Notebook        3         Baixo
1     Mouse       15          Alto
2   Teclado        8         Médio
3   Monitor        2         Baixo
4    Webcam       12          Alto