## Case 17 - classificação de pedidos

Uma empresa quer analisar pedidos.

Você recebeu os dados:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- valor_pedido: 120, 250, 80, 300, 150  

Crie um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada categoria_pedido com esta regra:  
  - "Pequeno" para pedidos menores que 100  
  - "Médio" para pedidos maiores ou iguais a 100 e menores que 200  
  - "Grande" para pedidos maiores ou iguais a 200  

- mostre apenas os pedidos classificados como Grande

In [ ]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

pedidos = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'valor_pedido': [120, 250, 80, 300, 150]
})

pedidos

   cliente  valor_pedido
0      Ana           120
1    Bruno           250
2   Carlos            80
3  Daniela           300
4      Eva           150

In [ ]:
# 'filtro' guarda as regras para classificar os pedidos por valor.
# 'valores' define o rótulo de cada faixa.
# np.select aplica as condições e cria a coluna 'categoria_pedido'.
filtro = [
    pedidos['valor_pedido'] >= 200,
    (pedidos['valor_pedido'] >= 100) & (pedidos['valor_pedido'] < 200),
    pedidos['valor_pedido'] < 100
]

valores = ['Grande', 'Médio', 'Pequeno']

pedidos['categoria_pedido'] = np.select(filtro, valores)

pedidos

   cliente  valor_pedido categoria_pedido
0      Ana           120            Médio
1    Bruno           250           Grande
2   Carlos            80          Pequeno
3  Daniela           300           Grande
4      Eva           150            Médio

In [5]:
# Filtrando para mostra apenas categoria_pedido grande
pedidos[pedidos['categoria_pedido'] == 'Grande']

   cliente  valor_pedido categoria_pedido
1    Bruno           250           Grande
3  Daniela           300           Grande