## Case 18 - classificação de desempenho de vendas

Uma empresa quer analisar o desempenho mensal de vendedores.

Você recebeu os dados:

- vendedor: Ana, Bruno, Carlos, Daniela, Eva  
- vendas_mes: 900, 1500, 700, 2000, 1200  

Crie um código com pandas + NumPy que:

- crie um DataFrame  

- crie uma coluna chamada desempenho com esta regra:  
  - "Baixo" para vendas menores que 1000  
  - "Médio" para vendas maiores ou iguais a 1000 e menores que 1800  
  - "Alto" para vendas maiores ou iguais a 1800  

- mostre apenas os vendedores com desempenho Alto

In [5]:
# Importando o pandas, Numpy e criando um data frame
import pandas as pd
import numpy as np

vendas = pd.DataFrame({
    'vendendor': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'venda_mes': [900, 1500, 700, 2000, 1200]
})

vendas

  vendendor  venda_mes
0       Ana        900
1     Bruno       1500
2    Carlos        700
3   Daniela       2000
4       Eva       1200

In [ ]:
# Cria as condições booleanas para classificar o desempenho:
# Alto para vendas >= 1800, Médio para vendas entre 1000 e 1799, e Baixo para vendas menores que 1000.
# A lista 'valores' define o rótulo que será aplicado quando cada condição for verdadeira.
# np.select usa essas regras para criar a coluna 'desempenho'.
filtro = [
    vendas['venda_mes'] >= 1800,
    (vendas['venda_mes'] >= 1000) & (vendas['venda_mes'] < 1800),
    vendas['venda_mes'] < 1000
]

valores = ['Alto', 'Médio', 'Baixo']

vendas['desempenho'] = np.select(filtro, valores)

vendas

  vendendor  venda_mes desempenho
0       Ana        900      Baixo
1     Bruno       1500      Médio
2    Carlos        700      Baixo
3   Daniela       2000       Alto
4       Eva       1200      Médio

In [ ]:
# Filtra e mostra apenas os vendedores classificados com desempenho 'Alto'.
vendas[vendas['desempenho'] == 'Alto']

  vendendor  venda_mes desempenho
3   Daniela       2000       Alto