
## Case 37 - remoção de valores faltantes com dropna

Use os mesmos dados originais:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, None, RJ, SP  
- valor_pedido: 120, 250, 80, None, 150  

Faça um código com pandas que:

- crie o DataFrame  
- remova as linhas que tenham qualquer valor faltante usando dropna()  
- mostre o resultado final

In [1]:
# Importando o pandas e criando um data frame
import pandas as pd

# Criando um DataFrame com alguns valores faltantes
clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', None, 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, None, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos   None          80.0
3  Daniela     RJ           NaN
4      Eva     SP         150.0

In [4]:
# Visualizamos primeiro qual colunas falta dados
clientes.isna().sum()

cliente         0
cidade          1
valor_pedido    1
dtype: int64

In [ ]:
# Usando DropNa para remover linhas com valores faltantes
clientes.dropna()   # ele retorna um novo DataFrame, sem modificar a tabela original

  cliente cidade  valor_pedido
0     Ana     SP         120.0
1   Bruno     RJ         250.0
4     Eva     SP         150.0