## Case 38 - remoção condicional de valores faltantes

Use os mesmos dados originais:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, None, RJ, SP  
- valor_pedido: 120, 250, 80, None, 150  

Faça um código com pandas que:

- crie o DataFrame  
- remova apenas as linhas em que valor_pedido está faltando  
- mostre o resultado final

In [2]:
# Importando o pandas e criando um data frame
import pandas as pd

# Criando um DataFrame com alguns valores faltantes
clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', None, 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, None, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos   None          80.0
3  Daniela     RJ           NaN
4      Eva     SP         150.0

In [3]:
# Msotrando a quantidade de valor faltando em cada coluna
clientes.isna().sum()

cliente         0
cidade          1
valor_pedido    1
dtype: int64

In [4]:
# Remove apenas as linha em que o dados está faltando em uma determinada coluna
clientes.dropna(subset=['valor_pedido']) # Retorna outra DataFrame

  cliente cidade  valor_pedido
0     Ana     SP         120.0
1   Bruno     RJ         250.0
2  Carlos   None          80.0
4     Eva     SP         150.0