## Case 39 - preenchimento com média

Use os mesmos dados originais:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, None, RJ, SP  
- valor_pedido: 120, 250, 80, None, 150  

Faça um código com pandas que:

- crie o DataFrame  
- calcule a média da coluna valor_pedido ignorando o valor faltante  
- preencha o valor faltante de valor_pedido com essa média  
- mostre o resultado final

In [ ]:
# Importando o pandas e criando um data frame
import pandas as pd

# Criando um DataFrame com alguns valores faltantes
clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', None, 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, None, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos   None          80.0
3  Daniela     RJ           NaN
4      Eva     SP         150.0

In [ ]:
# Calculando a média da coluna valor_pedido 
media = clientes['valor_pedido'].mean()   # Principais funções de agregação ignoran números faltantes   

# Usando o fillna para substituir apenas uma coluna especifica 
# Depois trocaremos os valores faltantes pela média da coluna
clientes['valor_pedido'] = clientes['valor_pedido'].fillna(media)

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos   None          80.0
3  Daniela     RJ         150.0
4      Eva     SP         150.0