## Case 40 - preenchimento com moda

Use os mesmos dados originais:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, None, RJ, SP  
- valor_pedido: 120, 250, 80, None, 150  

Faça um código com pandas que:

- crie o DataFrame  
- descubra a moda da coluna cidade  
- preencha o valor faltante de cidade com essa moda  
- mostre o resultado final

In [30]:
# Importando o pandas e criando um data frame
import pandas as pd

# Criando um DataFrame com alguns valores faltantes
clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', None, 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, None, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos   None          80.0
3  Daniela     RJ           NaN
4      Eva     SP         150.0

In [33]:
# Calculando a moda 
moda = clientes['cidade'].mode()[0] # Em caso de conter 2 valores que mais se repetem o dado gerado vai ser uma serie com [0] no final pega somente a primeira

# Usando o fillna para substituir apenas uma coluna especifica 
# Depois trocaremos os valores faltantes pela moda de palavra em cidade
clientes['cidade'] = clientes['cidade'].fillna(moda)

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos     RJ          80.0
3  Daniela     RJ           NaN
4      Eva     SP         150.0