## Case 41 - preenchimentos combinados

Use os mesmos dados originais:

- cliente: Ana, Bruno, Carlos, Daniela, Eva  
- cidade: SP, RJ, None, RJ, SP  
- valor_pedido: 120, 250, 80, None, 150  

Faça um código com pandas que:

- crie o DataFrame  
- preencha cidade com a moda  
- preencha valor_pedido com a média  
- mostre o DataFrame final sem valores faltantes

In [1]:
# Importando o pandas e criando um data frame
import pandas as pd

# Criando um DataFrame com alguns valores faltantes
clientes = pd.DataFrame({
    'cliente': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eva'],
    'cidade': ['SP', 'RJ', None, 'RJ', 'SP'],
    'valor_pedido': [120, 250, 80, None, 150,]
})

clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos   None          80.0
3  Daniela     RJ           NaN
4      Eva     SP         150.0

In [4]:
# Atribuindo valores para substituir valores null
media = clientes['valor_pedido'].mean() # Pegando a média
moda = clientes['cidade'].mode()[0]     # Em caso de conter 2 valores que mais se repetem o dado gerado vai ser uma serie com [0] no final pega somente a primeira

# Usando o fillna para substituir apenas algumas colunas especificas
# Trocando pelas atribuições desejadas 
clientes['valor_pedido'] = clientes['valor_pedido'].fillna(media)
clientes['cidade'] = clientes['cidade'].fillna(moda)

# Um data set com valores tratados, não apenas retirados
clientes

   cliente cidade  valor_pedido
0      Ana     SP         120.0
1    Bruno     RJ         250.0
2   Carlos     RJ          80.0
3  Daniela     RJ         150.0
4      Eva     SP         150.0

## Case 41 — conferir se ainda restam nulos

Use o mesmo DataFrame já tratado do exercício anterior e faça um código que:

- mostre quantos valores faltantes existem em cada coluna  
- confirme que o DataFrame está sem nulos

In [ ]:
# Pegando a soma de dados faltantes de cada coluna
clientes.isna().sum()

# Outra forma para confirma se tem dados null. Retorna True ou false caso há dados faltantes ainda
not clientes.isna().any().any()

True